{{- /*
SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and .Values.jwtKey.create (not .Values.accounting.external) (not .Values.controller.external) }}
{{- /* https://github.com/helm/helm-www/issues/1259 */}}
{{- $secretName := include "slurm.authJwtHs256Ref.name" . -}}
{{- $secret := lookup "v1" "Secret" (include "slurm.namespace" .) $secretName -}}
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "slurm.namespace" . }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.jwtKey.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "slurm.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "slurm.authJwtHs256Ref.key" . }}: {{ randAscii 1024 | b64enc }}
immutable: true
{{- end }}{{- /* if not $secret */}}
{{- end }}{{- /* if and .Values.jwtKey.create (not .Values.accounting.external) (not .Values.controller.external) */}}
